apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "perforator.fullname" . }}-storage-config
  namespace: {{ .Release.Namespace }}
data:  
{{- if .Values.storage.config.useCustom }}  
  config.yaml: |- {{- tpl .Values.storage.config.custom . | nindent 4 }}
{{- else }}
  config.yaml: |- {{- tpl (.Files.Get "config/storage.yaml") . | nindent 4 }}
{{- end }}