apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "perforator.fullname" . }}-gc-config
  namespace: {{ .Release.Namespace }}
data:  
{{- if .Values.gc.config.useCustom }}  
  config.yaml: |- {{- tpl .Values.gc.config.custom . | nindent 4 }}
{{- else }}
  config.yaml: |- {{- tpl (.Files.Get "config/gc.yaml") . | nindent 4 }}
{{- end }}