{{- if .Values.gc.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "perforator.gc.service.name" . }}-metrics
  labels:
    {{- include "perforator.selectorLabels" . | nindent 4 }}
    {{- include "perforator.gc.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
  namespace: {{ .Release.Namespace }}
  {{- with .Values.gc.metrics.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    {{- include "perforator.selectorLabels" . | nindent 4 }}
    {{- include "perforator.gc.selectorLabels" . | nindent 4 }}
  type: {{ .Values.gc.metrics.service.type }}
  {{- with .Values.gc.metrics.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  ports:
  - name: metrics
    port: {{ .Values.gc.metrics.service.ports.metrics.port }}
    targetPort: metrics
    {{- with .Values.gc.metrics.service.ports.metrics.nodePort }}
    nodePort: {{ . }}
    {{- end }}
  {{- range .Values.gc.metrics.service.ipFamilies }}
  ipFamilies:
    - {{ . }}
  {{- end}}
{{- end }}