{{- if .Values.web.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "perforator.fullname" . }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "perforator.selectorLabels" . | nindent 4 }}
    {{- include "perforator.web.selectorLabels" . | nindent 4 }}
  {{- with .Values.web.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      {{- include "perforator.selectorLabels" . | nindent 6 }}
      {{- include "perforator.web.selectorLabels" . | nindent 6 }}
  {{- with .Values.web.deployment.updateStrategy }}
  updateStrategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "perforator.selectorLabels" . | nindent 8 }}
        {{- include "perforator.web.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.web.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      dnsPolicy: {{ .Values.web.dnsPolicy }}
      {{- end }}
      containers:
      - name: {{ include "perforator.fullname" . }}-web
        image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.web.image.pullPolicy }}
        args: 
        - /perforator/web
        - --config=/etc/perforator/config.yaml
        - --log-level={{ .Values.web.logLevel }}
          {{- range .Values.web.extraArgs }}
        - {{ . }}
          {{- end}}
        resources:
        {{- toYaml .Values.web.resources | nindent 10 }}
        securityContext:
            {{- toYaml .Values.web.securityContext | nindent 10 }}
        {{- if .Values.web.useHostNetwork }}
        {{- end }}
        {{- with .Values.web.priorityClassName }}
        priorityClassName: {{ . }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.web.containerPorts.http }}
          name: http
        - containerPort: {{ .Values.web.containerPorts.grpc }}
          name: grpc
        - containerPort: {{ .Values.web.containerPorts.metrics }}
          name: metrics
        volumeMounts:
        - name: storage-s3-keys
          mountPath: "/etc/perforator/s3"
        - name: config
          mountPath: /etc/perforator/
        {{- if .Values.web.mounts.varlog }}
        - name: varlog
          mountPath: /var/log
          readOnly: true
        {{- end }}
        {{- if .Values.web.mounts.dockercontainers }}
        - name: dockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        {{- end }}
        {{- range .Values.web.mounts.extra }}
          - name: {{ .name }}
            mountPath: {{ .mountPath }}
            subPath: {{ .subPath }}
            readOnly: {{ .readOnly }}
        {{- end }}
      volumes:
      - name: storage-s3-keys
        secret:
          secretName: {{ include "perforator.secretName.s3" . }}
      - name: config
        configMap:
          name: {{ include "perforator.fullname" . }}-web-config
      {{- if .Values.web.mounts.varlog }}
      - name: varlog
        hostPath:
          path: /var/log
      {{- end }}
      {{- if .Values.web.mounts.dockercontainers }}
      - name: dockercontainers
        hostPath:
          path: /var/lib/docker/containers
      {{- end }}
      {{- range .Values.web.mounts.extra }}
        - name: {{ .name }}
          configMap:
            name: {{ .configMap }}
      {{- end }}
      {{- with .Values.web.nodeSelector }}  
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}