storage:
  databases:
    postgres:
      auth:
        user: {{ .Values.databases.postgresql.user }}
        password_env: "POSTGRES_PASSWORD"
      db: {{ .Values.databases.postgresql.db }}
      endpoints: {{ toYaml .Values.databases.postgresql.endpoints | nindent 8 }}
      sslmode: {{ .Values.databases.postgresql.sslmode }}
    s3:
      endpoint: {{ .Values.databases.s3.endpoint }}
      secret_key_path: "/etc/perforator/s3/secret_key.txt"
      access_key_path: "/etc/perforator/s3/access_key.txt"
      insecure: {{ .Values.databases.s3.insecure }}
      force_path_style: {{ .Values.databases.s3.force_path_style }}
  binaries:
    meta: "postgres"
    bucket: {{ .Values.databases.s3.buckets.binaries }}
binary_provider:
  file_cache:
    max_size: "20G"
    max_items: 1000
    root_path: "/cache/binaries"
  max_simultaneous_downloads: 30

gsym_s3_bucket: {{ .Values.databases.s3.buckets.binariesGSYM }}
