{{- if .Values.databases.clickhouse.password -}}
apiVersion: v1
data:
  password: {{ .Values.databases.clickhouse.password | b64enc | quote }}
kind: Secret
metadata:
  name: {{ include "perforator.fullname" . }}-clickhouse-password
  namespace: {{ .Release.Namespace }}
{{- end -}}