apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "perforator.fullname" . }}-proxy-config
  namespace: {{ .Release.Namespace }}
data:  
{{- if .Values.proxy.config.useCustom }}  
  config.yaml: |- {{- tpl .Values.proxy.config.custom . | nindent 4 }}
{{- else }}
  config.yaml: |- {{- tpl (.Files.Get "config/proxy.yaml") . | nindent 4 }}
{{- end }}